name: ESLint
on: push
jobs:
    ESLint:
        name: Run linter and enforce style
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install ESLint
              run: npm i eslint eslint-config-standard
            - name: Run ESLint
              run: ./node_modules/eslint/bin/eslint.js src/pesterchum.js
